version: '3.7'

services:
  app:
    build: .
    command: gosu user uvicorn serve:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - "./serve.py:/code/serve.py"
      - "./convert_video_to_hls_vod.py:/code/convert_video_to_hls_vod.py"
      - "./hlsvodserve:/code/hlsvodserve"
      - "${WORK_DIR}:/work"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/version"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    image: quay.io/minio/minio:RELEASE.2022-06-03T01-40-53Z
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - "minio-data:/data"
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-data:
